import Head from 'next/head';
import {motion as m} from 'framer-motion';
import Signup from './auth/signup';

import { container, item } from "../animation";
import TodoCard from '../components/TodoCard';
import ProjectCard from '../components/ProjectCard';
import ProjectTypeCard from '../components/ProjectTypeCard';
import Link from 'next/link';
import { useContext, useEffect } from 'react';
import { AppContext } from '../contexts/AppContext';

export default function Home() {
  const { currentPage, setCurrentPage, changeCurrentPageName } = useContext(AppContext);

  useEffect(() => {
    changeCurrentPageName('/');
  }, [currentPage, setCurrentPage]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <main>
        <section className='flex-1 flex '>

          <div className='flex-1 md:flex hidden flex-col'>
            <div className='flex flex-col items-center p-5'>
              <ProjectCard brandName="DevTask" members='9' startD="12th may" deadL="20th may" pay="12,000" />
              <div className='flex w-full justify-between items-center space-x-3 mt-5'>
                <ProjectTypeCard />
                <div className='flex-1'>
                  <TodoCard description={"oewhi eiwhnri srir sfiusr fsuif srdufh rsdfo "} title="join us now" time={"12:30"}/>
                </div>
              </div>
            </div>
          </div>

          <div className='flex-1 flex flex-col items-center mt-5 px-10'>
            <h1 className='font-bold text-xl text-center'>Welcome to <span className='text-cyan-500 text-2xl'>DevTask</span></h1>
            <p className='text-center mt-3'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, aperiam necessitatibus id
              assumenda veritatis hic recusandae, totam deleniti qui illum alias delectus unde,
              nostrum quaerat non at tenetur. Minus, est.
              Alias ex corrupti excepturi a molestias assumenda impedit inventore
              unde tempore doloribus explicabo cupiditate non odio nesciunt nulla
              accusamus ducimus consequuntur necessitatibus sint distinctio, quae
              exercitationem esse quos dignissimos! Facilis!
            </p>

            <Link href="/auth/signup">
              <button className='py-2 px-20 rounded-md font-medium text-lg text-white flex-1 mt-20 bg-cyan-500'>Get Started</button>
            </Link>
          </div>
        </section>

        {/* <m.div variants={container} inherit="hidden" animate="show" className='w-full text-center py-36 font-semibold text-2xl text-slate-400'>
          <div className='overflow-hidden'>
            <m.h1 variants={item} className='pb-2'>Hey shedrack</m.h1>
          </div>
          <div className='overflow-hidden'>
            <m.p variants={item} className='pb-2'>Add your first project</m.p>
          </div>
        </m.div> */}
      </main>
    </div>
  )
}
